platform:ios,'8.0'

target 'FGProject' do
    pod 'Masonry'
    pod 'AFNetworking','3.2.0'
    pod 'SDWebImage'
    pod 'SVProgressHUD'
    pod 'pop'
    pod 'Firebase'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'
    pod 'Firebase/Core'
    pod 'Firebase/AdMob'
    pod 'JCAlertView'
    pod 'PNChart'
end

