platform:ios,'8.0'

target 'FGProject' do
pod 'Masonry'
pod 'FBMemoryProfiler'
pod 'FLEX'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'pop'
pod 'JSPatchPlatform'
pod 'CocoaAsyncSocket'
pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'Firebase/Messaging'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'JCAlertView'
pod 'PNChart'
end

